# This workflow will run on a Pull Request is created on both master develop
# It run as series of checks from the Integration Developement Checklist


name: Run Integration Development Checklist

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  run-integration-development-checklist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Polarity Integration Development Checklist
      id: int-dev-checklist
      uses: polarityio/polarity-integration-development-checklist@v1.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
